import {INPUT_BASE_CURRENCY,INPUT_SECOND_CURRENCY, SELECT_BASE_CURRENCY, SELECT_SECOND_CURRENCY, SET_CONVERSION_RATES, GET_CONVERSION_DATA, SET_DATE_CURRENCY_RATE, GET_DATE_CURRENCY_RATE, CHANGE_DISPLAY, CHANGE_VALUE, CLOSE_DISPLAY, FETCH_ERROR} from '../constants'

export const setConversionRates = () => async (dispatch, getState) => {

}