
export const INPUT_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY_INPUT'
export const INPUT_TARGET_CURRENCY = 'CHANGE_TARGET_CURRENCY_INPUT'

export const SELECT_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY_INPUT'
export const SELECT_TARGET_CURRENCY = 'CHANGE_TARGET_CURRENCY_INPUT'

export const SET_CONVERSION_RATES = 'SET_CONVERSION_RATES'

export const GET_CONVERSION_DATA = 'GET_CONVERSION_DATA'
export const SET_DATE_CURRENCY_RATE = 'CHANGE_DISPLAY'
export const GET_DATE_CURRENCY_RATE = 'CHANGE_DISPLAY'
export const SET_BASE = 'SET_BASE'
export const SET_THEME = 'SET_THEME'
export const FETCH_ERROR = 'FETCH_ERROR'